name: README build

on:
  push:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Master branch
        uses: actions/checkout@v1
	  - name: Setup NodeJs 13.x
		uses: actions/setup-node@v1
		with:
		  node-version: "13.x"
	  - name: Cache dependencies and build outputs to improve workflow execution time.
		uses: actions/cache@v1
		with:
		  path: node_modules
		  key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
	  - name: Install dependencies
		run: npm install
	  - name: Generate README file
		run: node index.js
	  - name: Commit and Push new README.md to the repository
		uses: DeeEmm/publish-to-github-action@master
		env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}