name: README build

on:
  schedule:
	- cron: '0 * */5 * *'

jobs:
  build:
	runs-on: ubuntu-latest

	steps:
	  - name: Generate README file
		run: node index.js
	  - name: Commit and Push new README.md to the repository
		uses: DeeEmm/publish-to-github-action@master
		env:
		  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}